---
# Source: neptune/charts/mysql/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: neptone-mysql-secret
  namespace: neptone
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: neptone
    app.kubernetes.io/created-by: xxxxx
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
  MYSQL_DATABASE: bmVwdHVuZQ==
  MYSQL_USER: bmVwdHVuZQ==
  MYSQL_PASSWORD: bmVwdHVuZQ==
---
# Source: neptune/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: neptone-neptune-secret
  namespace: neptone
  labels:
    app.kubernetes.io/name: neptune
    app.kubernetes.io/part-of: neptone
    app.kubernetes.io/created-by: xxxxx
data:
  NEPTUNE_API_DATABASE_URI: bXlzcWwrcHlteXNxbDovL25lcHR1bmU6bmVwdHVuZUBuZXB0b25lLW15c3FsOjMzMDYvbmVwdHVuZQ==
---
# Source: neptune/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: neptone-neptune-config
  namespace: neptone
  labels:
    app.kubernetes.io/name: neptune
    app.kubernetes.io/part-of: neptone
    app.kubernetes.io/created-by: xxxxx
data:
  NEPTUNE_API_ENV: production
  NEPTUNE_API_DEBUG: "0"
  NEPTUNE_API_TESTING: "0"
---
# Source: neptune/charts/mysql/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: neptone-mysql
  namespace: neptone
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: neptone
    app.kubernetes.io/created-by: xxxxx
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: neptone
    app.kubernetes.io/created-by: xxxxx
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
# Source: neptune/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: neptone-neptune
  namespace: neptone
  labels:
    app.kubernetes.io/name: neptune
    app.kubernetes.io/part-of: neptone
    app.kubernetes.io/created-by: xxxxx
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: neptune
    app.kubernetes.io/part-of: neptone
    app.kubernetes.io/created-by: xxxxx
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
# Source: neptune/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neptone-neptune
  namespace: neptone
  labels:
    app.kubernetes.io/name: neptune
    app.kubernetes.io/part-of: neptone
    app.kubernetes.io/created-by: xxxxx
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: neptune
      app.kubernetes.io/part-of: neptone
      app.kubernetes.io/created-by: xxxxx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: neptune
        app.kubernetes.io/part-of: neptone
        app.kubernetes.io/created-by: xxxxx
    spec:
      containers:
        - name: neptune
          image: haditsn/nepton:f6f565dbe7f3b85f6a4544b12a020e9382196d4a
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: neptone-neptune-config
                optional: true
            - secretRef:
                name: neptone-neptune-secret
          livenessProbe:
            initialDelaySeconds: 1
            periodSeconds: 3
            exec:
              command: ["kill", "-0", "1"]
          readinessProbe:
            initialDelaySeconds: 1
            periodSeconds: 3
            tcpSocket:
              port: 8080
---
# Source: neptune/templates/hpa.yml
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: neptone-neptune-hpa
  namespace: neptone
  labels:
    app.kubernetes.io/name: neptune
    app.kubernetes.io/part-of: neptone
    app.kubernetes.io/created-by: xxxxx
spec:
  scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name:  neptone-neptune
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
  resource:
    name: cpu
    target:
      type: Utilization
      averageUtilization: 50
---
# Source: neptune/charts/mysql/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neptone-mysql
  namespace: neptone
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: neptone
    app.kubernetes.io/created-by: xxxxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/part-of: neptone
      app.kubernetes.io/created-by: xxxxx
  serviceName: neptone-mysql
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/part-of: neptone
        app.kubernetes.io/created-by: xxxxx
    spec:
      containers:
        - name: mysql
          image: mysql:8
          envFrom:
            - secretRef:
                name: neptone-mysql-secret
          volumeMounts:
            - name: neptone-mysql-data
              mountPath: /var/lib/mysql
          livenessProbe:
            initialDelaySeconds: 1
            periodSeconds: 3
            exec:
              command: ["ls", "/proc/1"]
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            exec:
              command:
                - bash
                - -c
                - >-
                  mysql -h localhost
                  -u${MYSQL_USER} -p${MYSQL_PASSWORD}
                  -e "select version();"
  volumeClaimTemplates:
    - metadata:
        name: neptone-mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
