apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
data:
  NEPTUNE_API_ENV: {{ .Values.neptune.config.env }}
  NEPTUNE_API_DEBUG: {{ .Values.neptune.config.debug | ternary "1" "0" | quote }}
  NEPTUNE_API_TESTING: {{ .Values.neptune.config.testing | ternary "1" "0" | quote }}
