apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  selector:
    {{- include "labels" . | nindent 4 }}
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: 3306
