neptune:
  deployment:
    replicas: 3

  image:
    repository: jecibah771/nepton
    tag: latest

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    host: neptune.20302040.xyz
    annotations:
    ingressClassName:

  config:
    env: production
    debug: false
    testing: false

  sealedSecrets:
    enabled: false

mysql:
  image:
    repository: mysql
    tag: 8

  persistentVolumeClaim:
    accessMode: ReadWriteOnce
    size: 20Gi

  service:
    type: ClusterIP
    port: 3306

  secret:
    mysqlRootPassword: root
    mysqlDatabase: neptune
    mysqlUser: neptune
    mysqlPassword: neptune

  sealedSecrets:
    enabled: false
