apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neptune
  namespace: argocd
spec:
  project: neptune
  source:
    repoURL: https://github.com/xxxxx/neptune.git
    ref: master
    path: ./manifests/overlays/production
  destination:
    name: in-cluster
    namespace: neptune
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
