name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to  docker hub
      uses: docker/login-action@v2
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v2
      with: 
         images: haditsn/nepton
         
    - name: Build and  push  Docker image
      uses: docker/build-push-action@v2
      with:
        content: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        lables: ${{ steps.meta.outputs.labels }}
        
    - name: test
      run:  ls -ltr
