name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to  docker hub
      uses: docker/login-action@v2
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      env:
        commit_id: ${{ github.sha }}
      run: |
           docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/nepton:${{ github.sha }}
           docker push  ${{ secrets.DOCKERHUB_USERNAME }}/nepton:${{ github.sha }}
           
    - name: test
      run:  ls -ltr
      
    - name: Install helm
      run: |
          curl -LO https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
          tar -zxvf helm-v3.8.0-linux-amd64.tar.gz
          mv linux-amd64/helm /usr/local/bin/helm
          helm version
          
    - name: Deploy
      run: |
          helm template charts/neptune --set neptone.image.tage=${{ github.sha }}
      
