name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to  docker hub
      uses: docker/login-action@v2
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      env:
        commit_id: ${{ github.sha }}
      run: |
           docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/nepton:${{ github.sha }}
           docker push  ${{ secrets.DOCKERHUB_USERNAME }}/nepton:${{ github.sha }}
           
    - name: test
      run:  ls -ltr
      
    - name: create helm template
      uses: hiberbee/github-action-helm@latest
      run: helm template charts/nepton
           
    - name: hadi
      run:  ls -ltr 
      
